export const orders = [
  {
    id: "ORD001",
    customerName: "Alice Johnson",
    date: "2025-05-15T14:30:00Z",
    price: 49.99,
    paymentType: "Credit Card",
    orderType: "Delivery",
    status: "new", // 🔸 статус должен соответствовать значению таба
    platform: "Web",
  },
  {
    id: "ORD002",
    customerName: "Bob Smith",
    date: "2025-05-14T11:00:00Z",
    price: 24.5,
    paymentType: "PayPal",
    orderType: "Pickup",
    status: "in_progress",
    platform: "Mobile",
  },
  {
    id: "ORD003",
    customerName: "Charlie Brown",
    date: "2025-05-13T16:45:00Z",
    price: 75.0,
    paymentType: "Cash",
    orderType: "Delivery",
    status: "late",
    platform: "Web",
  },
  {
    id: "ORD004",
    customerName: "Dana White",
    date: "2025-05-12T09:20:00Z",
    price: 60.0,
    paymentType: "Credit Card",
    orderType: "Pickup",
    status: "ready",
    platform: "Kiosk",
  },
  {
    id: "ORD005",
    customerName: "Evan Davis",
    date: "2025-05-11T13:15:00Z",
    price: 38.75,
    paymentType: "PayPal",
    orderType: "Delivery",
    status: "on_the_way",
    platform: "Web",
  },
  {
    id: "ORD006",
    customerName: "Fiona Hill",
    date: "2025-05-10T15:00:00Z",
    price: 89.99,
    paymentType: "Credit Card",
    orderType: "Delivery",
    status: "history",
    platform: "Mobile",
  },
];
