export const orders = [
  {
    id: "ORD001",
    customerName: "Alice Johnson",
    date: "2025-05-15T14:30:00Z",
    price: 49.99,
    paymentType: "Credit Card",
    orderType: "Delivery",
    status: "new",
    platform: "Web",
  },
  {
    id: "ORD002",
    customerName: "Bob Smith",
    date: "2025-05-14T11:00:00Z",
    price: 24.5,
    paymentType: "PayPal",
    orderType: "Pickup",
    status: "in_progress",
    platform: "Mobile",
  },
  {
    id: "ORD003",
    customerName: "Charlie Brown",
    date: "2025-05-13T16:45:00Z",
    price: 75.0,
    paymentType: "Cash",
    orderType: "Delivery",
    status: "late",
    platform: "Web",
  },
  {
    id: "ORD004",
    customerName: "Dana White",
    date: "2025-05-12T09:20:00Z",
    price: 60.0,
    paymentType: "Credit Card",
    orderType: "Pickup",
    status: "ready",
    platform: "Kiosk",
  },
  {
    id: "ORD005",
    customerName: "Evan Davis",
    date: "2025-05-11T13:15:00Z",
    price: 38.75,
    paymentType: "PayPal",
    orderType: "Delivery",
    status: "on_the_way",
    platform: "Web",
  },
  {
    id: "ORD006",
    customerName: "Fiona Hill",
    date: "2025-05-10T15:00:00Z",
    price: 89.99,
    paymentType: "Credit Card",
    orderType: "Delivery",
    status: "history",
    platform: "Mobile",
  },
  {
    id: "ORD007",
    customerName: "George Clark",
    date: "2025-05-09T18:30:00Z",
    price: 52.45,
    paymentType: "Cash",
    orderType: "Pickup",
    status: "ready",
    platform: "Web",
  },
  {
    id: "ORD008",
    customerName: "Hannah Lee",
    date: "2025-05-08T20:10:00Z",
    price: 44.0,
    paymentType: "PayPal",
    orderType: "Delivery",
    status: "in_progress",
    platform: "Mobile",
  },
  {
    id: "ORD009",
    customerName: "Ian Miller",
    date: "2025-05-07T08:45:00Z",
    price: 63.5,
    paymentType: "Credit Card",
    orderType: "Pickup",
    status: "new",
    platform: "Kiosk",
  },
  {
    id: "ORD010",
    customerName: "Julia Adams",
    date: "2025-05-06T10:00:00Z",
    price: 71.99,
    paymentType: "Cash",
    orderType: "Delivery",
    status: "late",
    platform: "Web",
  },
  {
    id: "ORD011",
    customerName: "Kevin Turner",
    date: "2025-05-05T12:15:00Z",
    price: 29.5,
    paymentType: "Credit Card",
    orderType: "Pickup",
    status: "on_the_way",
    platform: "Mobile",
  },
  {
    id: "ORD012",
    customerName: "Laura Scott",
    date: "2025-05-04T14:00:00Z",
    price: 55.0,
    paymentType: "PayPal",
    orderType: "Delivery",
    status: "history",
    platform: "Web",
  },
  {
    id: "ORD013",
    customerName: "Mike Ross",
    date: "2025-05-03T17:45:00Z",
    price: 40.0,
    paymentType: "Credit Card",
    orderType: "Pickup",
    status: "ready",
    platform: "Kiosk",
  },
  {
    id: "ORD014",
    customerName: "Nina Diaz",
    date: "2025-05-02T19:30:00Z",
    price: 78.25,
    paymentType: "Cash",
    orderType: "Delivery",
    status: "new",
    platform: "Mobile",
  },
  {
    id: "ORD015",
    customerName: "Oscar Knight",
    date: "2025-05-01T07:20:00Z",
    price: 33.0,
    paymentType: "PayPal",
    orderType: "Pickup",
    status: "late",
    platform: "Web",
  },
];
